#include "DHT.h"
//#include <NewPing.h>
#include "Arduino.h"
#include <HardwareSerial.h>
#include "Separador.h"
#include "Motor.h"
#include "Relays.h"
#include <ESP32Time.h>
#include <PubSubClient.h>
#include <WiFi.h>
#include "PIDController.h"
#include "GravityTDS.h"
#include <Wire.h> 
#include "analogWrite.h"
#include "ADS1115_PARALLEL.h"
#include <EEPROM.h>
#include <string.h>
//#include "AiEsp32RotaryEncoder.h"
